Did 1-st task and write tests from him
Paulsams/formal-lang-course pull request #1
Opened 2023-02-22 17:40 UTC by Paulsams

Сделал модуль с двумя функциями-утилитами, которые были прописаны в задаче и написал небольшие тесты для них, которые запускаются через CI.

2023-02-23 14:20 UTC, rustam-azimov requested changes

2023-02-23 14:20 UTC, rustam-azimov commented on project/graph_utils.py
> +def get_graph_info(name: str) -> Tuple[int, int, list]:
Поменяйте лучше на named tuple

2023-02-23 14:20 UTC, rustam-azimov commented on project/graph_utils.py
> +    graph = cfpq_data.labeled_two_cycles_graph(count_nodes_in_cycle, labels)
Кажется эта функция должна принимать n и m - длины циклов, и labels=labels передать тут стоит.

2023-02-23 14:20 UTC, rustam-azimov commented on tests/test_graph_utils_create_labeled_graph_with_two_cycle_and_save_to_file.py
> +        10, {"a", "b"}, path_to_file
Для всех графов, которые создаете нужно сравнить в тестах их с ожидаемыми графами, например с ожидаемым файлом в формате dot.

2023-02-23 14:20 UTC, rustam-azimov commented on tests/test_graph_utils_get_graph_info.py
> +    assert graph_utils.get_graph_info("skos")
Нужно проверить корректность полученной информации о графах

2023-02-23 22:33 UTC, Paulsams commented on project/graph_utils.py
> +def get_graph_info(name: str) -> Tuple[int, int, list]:
Окей, узнал что это. Поправил.

2023-02-23 22:34 UTC, Paulsams commented on project/graph_utils.py
> +    graph = cfpq_data.labeled_two_cycles_graph(count_nodes_in_cycle, labels)
И правда. Не так понял задание, значит). Тоже исправил.

2023-02-23 22:35 UTC, Paulsams commented on tests/test_graph_utils_create_labeled_graph_with_two_cycle_and_save_to_file.py
> +        10, {"a", "b"}, path_to_file
Ну вроде сделал ожидаемые файлы: читаю и то, и то -- и сравниваю представление в виде графа.

2023-02-23 22:35 UTC, Paulsams commented on tests/test_graph_utils_get_graph_info.py
> +    assert graph_utils.get_graph_info("skos")
А, увидел на сайте данные обо всех графах. Добавил проверку.

2023-02-24 05:44 UTC, rustam-azimov approved these changes

2023-02-24 14:06 UTC, merged