Did 4-nd task
Paulsams/formal-lang-course pull request #4
Opened 2023-03-16 23:05 UTC by Paulsams

2023-03-20 21:45 UTC, Paulsams commented
Ой, я совсем забыл Вас добавить в проверяющих, но сделал я это ДЗ к мягкому дедлайну. Простите за это).

2023-03-23 07:58 UTC, rustam-azimov requested changes
Добавьте также функцию, которая принимает граф, запрос, множество стартовых, множество финальных, и separately.

2023-03-27 10:49 UTC, Paulsams commented
> Добавьте также функцию, которая принимает граф, запрос, множество стартовых, множество финальных, и separately.

Немного поздновато поправил, так как был завал по другим предметам, но в общем добавил функцию и в одном тесте проверяю ещё через неё.

2023-03-29 08:36 UTC, rustam-azimov approved these changes

2023-03-31 18:26 UTC, merged