Task 5
Paulsams/formal-lang-course pull request #5
Opened 2023-04-01 23:18 UTC by Paulsams

2023-04-01 23:23 UTC, Paulsams commented
Я опять заколебался и ещё вчера сделал задание, но во-первых сделал локально коммит в main, так ещё ничего не запушил, xDD). Сейчас только услышал, что Вы у кого-то проверили и резко понял, что забыл же пулл реквест создать. Так что извините).

2023-04-02 08:55 UTC, rustam-azimov requested changes

2023-04-02 08:55 UTC, rustam-azimov commented on project/cfg_utils.py
> +        cfg.remove_useless_symbols()
Эту строку можно убрать

2023-04-02 12:14 UTC, Paulsams commented on project/cfg_utils.py
> +        cfg.remove_useless_symbols()
Хорошо, понял. Убрал.

2023-04-07 13:26 UTC, rustam-azimov approved these changes

2023-04-07 20:46 UTC, merged